export const WEAPONS = [
  {
    id: 'greatsword',
    name: '大剣',
    en: 'GREAT SWORD',
    category: '切断',
    power: 48,
    speed: 1.05,
    reach: 5.2,
    stamina: 15,
    guard: true,
    special: '溜め斬り',
    detail: '長押しで3段階に溜める。隙を読んで一撃を叩き込む。',
    color: '#d7c394',
  },
  {
    id: 'longsword',
    name: '太刀',
    en: 'LONG SWORD',
    category: '切断',
    power: 26,
    speed: 0.58,
    reach: 5.7,
    stamina: 9,
    guard: false,
    special: '気刃斬り',
    detail: '連撃で練気を蓄積。気刃斬りで練気を解放し、攻撃をいなす。',
    color: '#b2cad5',
  },
  {
    id: 'swordshield',
    name: '片手剣',
    en: 'SWORD & SHIELD',
    category: '切断',
    power: 21,
    speed: 0.42,
    reach: 4.1,
    stamina: 6,
    guard: true,
    special: 'ジャストラッシュ',
    detail: '素早い連撃と盾。特殊攻撃は踏み込む多段ラッシュ。',
    color: '#9ac8b2',
  },
  {
    id: 'dualblades',
    name: '双剣',
    en: 'DUAL BLADES',
    category: '切断',
    power: 14,
    speed: 0.28,
    reach: 3.9,
    stamina: 5,
    guard: false,
    special: '鬼人化',
    detail: '鬼人化を切り替え、スタミナと引き換えに機動力と手数を増やす。',
    color: '#e78e7b',
  },
  {
    id: 'hammer',
    name: 'ハンマー',
    en: 'HAMMER',
    category: '打撃',
    power: 42,
    speed: 0.88,
    reach: 4.6,
    stamina: 13,
    guard: false,
    special: '溜め叩きつけ',
    detail: '長押しで溜め、頭部を狙って気絶を奪う。',
    color: '#d5ad6d',
  },
  {
    id: 'huntinghorn',
    name: '狩猟笛',
    en: 'HUNTING HORN',
    category: '打撃',
    power: 30,
    speed: 0.7,
    reach: 5,
    stamina: 10,
    guard: false,
    special: '回復・攻撃旋律',
    detail: '攻撃で音符を蓄積。演奏で周囲の仲間を回復し、攻撃力を高める。',
    color: '#debf79',
  },
  {
    id: 'lance',
    name: 'ランス',
    en: 'LANCE',
    category: '切断',
    power: 25,
    speed: 0.55,
    reach: 6,
    stamina: 8,
    guard: true,
    special: 'カウンター突き',
    detail: '強固な盾と長いリーチ。特殊攻撃中は反撃の構え。',
    color: '#aebecb',
  },
  {
    id: 'gunlance',
    name: 'ガンランス',
    en: 'GUNLANCE',
    category: '砲撃',
    power: 29,
    speed: 0.7,
    reach: 5.8,
    stamina: 10,
    guard: true,
    special: '竜撃砲',
    detail: '突きで熱量を蓄積。竜撃砲は肉質を無視する強力な砲撃。',
    color: '#baa38b',
  },
  {
    id: 'switchaxe',
    name: 'スラッシュアックス',
    en: 'SWITCH AXE',
    category: '切断',
    power: 32,
    speed: 0.67,
    reach: 5.6,
    stamina: 10,
    guard: false,
    special: '剣モード変形',
    detail: '斧と剣を切り替える。剣モードはゲージを消費して高火力。',
    color: '#d69e6a',
  },
  {
    id: 'chargeblade',
    name: 'チャージアックス',
    en: 'CHARGE BLADE',
    category: '切断',
    power: 25,
    speed: 0.58,
    reach: 4.8,
    stamina: 8,
    guard: true,
    special: '超高出力解放',
    detail: '剣撃でビンを溜め、斧の超高出力属性解放斬りで一気に放つ。',
    color: '#c5a1d8',
  },
  {
    id: 'insectglaive',
    name: '操虫棍',
    en: 'INSECT GLAIVE',
    category: '切断',
    power: 24,
    speed: 0.48,
    reach: 5.5,
    stamina: 8,
    guard: false,
    special: '跳躍・猟虫',
    detail: '跳躍攻撃で地上の攻撃をかわし、猟虫の追撃でエキスを得る。',
    color: '#9bd4be',
  },
  {
    id: 'lightbowgun',
    name: 'ライトボウガン',
    en: 'LIGHT BOWGUN',
    category: '射撃',
    power: 17,
    speed: 0.36,
    reach: 24,
    stamina: 3,
    guard: false,
    special: '速射',
    detail: '軽快に移動して射撃。8発ごとにリロード。適正距離で威力上昇。',
    color: '#a8bcaf',
  },
  {
    id: 'heavybowgun',
    name: 'ヘビィボウガン',
    en: 'HEAVY BOWGUN',
    category: '射撃',
    power: 38,
    speed: 0.8,
    reach: 28,
    stamina: 5,
    guard: true,
    special: '狙撃竜弾',
    detail: '重い一撃と盾。5発ごとにリロード。特殊弾は貫通する。',
    color: '#b7a691',
  },
  {
    id: 'bow',
    name: '弓',
    en: 'BOW',
    category: '射撃',
    power: 23,
    speed: 0.55,
    reach: 23,
    stamina: 10,
    guard: false,
    special: '竜の一矢',
    detail: '長押しで矢を溜める。回避と射撃のスタミナ配分が鍵。',
    color: '#ceb480',
  },
] as const;
export type WeaponId = (typeof WEAPONS)[number]['id'];
export const weapon = (id: WeaponId) => WEAPONS.find((w) => w.id === id)!;
export const MONSTERS = [
  {
    id: 'rathalos',
    name: 'リオレウス',
    title: '空の王者',
    en: 'RATHALOS',
    species: '飛竜種',
    stars: 2,
    biome: 'forest',
    habitat: '古代樹の森',
    color: '#b54a32',
    accent: '#e6ad63',
    hp: 1800,
    attack: 23,
    reward: 900,
    material: '火竜の鱗',
    weakness: '頭部 / 龍',
    description: '大きな翼で飛翔する雄の火竜。火球をかわし、着地の隙に頭部を狙え。',
    moves: ['bite', 'fire', 'charge', 'tail', 'leap'],
    size: 1,
  },
  {
    id: 'rathian',
    name: 'リオレイア',
    title: '陸の女王',
    en: 'RATHIAN',
    species: '飛竜種',
    stars: 1,
    biome: 'forest',
    habitat: '翡翠の密林',
    color: '#657f45',
    accent: '#d5c397',
    hp: 1400,
    attack: 18,
    reward: 700,
    material: '雌火竜の鱗',
    weakness: '頭部 / 龍',
    description: '地上を支配する雌の火竜。毒の尾を警戒し、突進後に反撃しよう。',
    moves: ['bite', 'charge', 'tail', 'fire'],
    size: 0.95,
  },
  {
    id: 'zinogre',
    name: 'ジンオウガ',
    title: '雷狼竜',
    en: 'ZINOGRE',
    species: '牙竜種',
    stars: 3,
    biome: 'mountain',
    habitat: '霊峰の渓流',
    color: '#2e7e8b',
    accent: '#edc96c',
    hp: 2200,
    attack: 26,
    reward: 1200,
    material: '雷狼竜の甲殻',
    weakness: '頭部 / 氷',
    description: '雷光を纏う牙竜。帯電時の雷撃を避け、前脚の叩きつけを見極める。',
    moves: ['bite', 'thunder', 'leap', 'tail', 'thunder'],
    size: 1.05,
  },
  {
    id: 'tigrex',
    name: 'ティガレックス',
    title: '轟竜',
    en: 'TIGREX',
    species: '飛竜種',
    stars: 3,
    biome: 'desert',
    habitat: '大蟻塚の荒地',
    color: '#d99542',
    accent: '#365e91',
    hp: 2300,
    attack: 28,
    reward: 1250,
    material: '轟竜の爪',
    weakness: '頭部 / 雷',
    description: '強靭な四肢で突進を繰り返す轟竜。進路を横切らず、側面へ回り込め。',
    moves: ['charge', 'bite', 'charge', 'roar', 'tail'],
    size: 1.1,
  },
  {
    id: 'nargacuga',
    name: 'ナルガクルガ',
    title: '迅竜',
    en: 'NARGACUGA',
    species: '飛竜種',
    stars: 3,
    biome: 'night',
    habitat: '月影の樹海',
    color: '#293d50',
    accent: '#b74240',
    hp: 1950,
    attack: 24,
    reward: 1150,
    material: '迅竜の黒毛',
    weakness: '頭部 / 雷',
    description: '暗がりから襲いかかる迅竜。赤く光る眼を追い、尻尾の叩きつけに備えよ。',
    moves: ['leap', 'tail', 'leap', 'charge', 'bite'],
    size: 1,
  },
  {
    id: 'rajang',
    name: 'ラージャン',
    title: '金獅子',
    en: 'RAJANG',
    species: '牙獣種',
    stars: 4,
    biome: 'volcano',
    habitat: '溶岩の峡谷',
    color: '#564637',
    accent: '#eec154',
    hp: 2700,
    attack: 32,
    reward: 1600,
    material: '金獅子の黒毛',
    weakness: '頭部 / 氷',
    description: '怒りにより金色に輝く牙獣。直線の雷光ブレスを横に避け、背後を取れ。',
    moves: ['punch', 'beam', 'leap', 'punch', 'roar'],
    size: 0.9,
  },
] as const;
export type MonsterId = (typeof MONSTERS)[number]['id'];
export type Biome = (typeof MONSTERS)[number]['biome'];
export type Move = (typeof MONSTERS)[number]['moves'][number];
export const monster = (id: MonsterId) => MONSTERS.find((m) => m.id === id)!;
export const MOVE_NAMES: Record<Move, string> = {
  bite: '噛みつき',
  fire: '火炎ブレス',
  charge: '突進',
  tail: '尻尾攻撃',
  leap: '跳躍攻撃',
  thunder: '落雷',
  roar: '咆哮',
  punch: '連続パンチ',
  beam: '雷光ブレス',
};
export const ITEMS = ['potion', 'antidote', 'trap', 'bomb', 'whetstone'] as const;
export type Item = (typeof ITEMS)[number];
export const ITEM_NAMES: Record<Item, string> = {
  potion: '回復薬',
  antidote: '解毒薬',
  trap: 'シビレ罠',
  bomb: '大タル爆弾',
  whetstone: '砥石',
};
export type Difficulty = 'normal' | 'veteran' | 'practice';
